versions:
    - 2.4
    - 2.3
    - 2.2
    - 2.1
    - 2.0.0
    - 1.9.3
    - 1.9.1
    - 1.9.2
    - 1.9.1
    - 1.8.7
    - 1.8.6

empty_version:
    version: ~
    default: 0
    bundler: 0
    gems: []
