versions:
    - 6.1.2
    - 6.1.1
    - 6.1.0
    - 6.0.1
    - 6.0.0
    - 5.6.6
    - 5.6.5
    - 5.6.4
    - 5.6.3
    - 5.6.2
    - 5.6.1
    - 5.6.0
    - 5.5.3
    - 5.5.2
    - 5.5.1
    - 5.5.0
    - 5.4.3
    - 5.4.2
    - 5.4.1
    - 2.4.6

empty_instance:
    name: ~
    jvm_options:
        - '-Xms2G'
        - '-Xmx2G'
