target: ~

vm:
    provider:
        aws:
            access_key_id: ACCESS KEY ID
            secret_access_key: SECRET ACCESS KEY
            machines:
                machine1:
                    id: aws1
                    hostname: aws1.puphpet
                    ssh_username: ubuntu
                    keypair_name: REGION KEYPAIR NAME
                    private_key_path: REGION PRIVATE KEY PATH
                    region: us-east-1
                    instance_type: t2.small
                    ami: ami-7b386c11
                    subnet_id: ~
                    elastic_ip: ~
                    security_groups:
                        - vagrant
                    tags:
                        Source: Puphpet
    provision:
        puppet:
            manifests_path: puphpet/puppet/manifests
            module_path:
                - puphpet/puppet/modules
                - puphpet/puppet/manifests
            options:
                - '--verbose'
                - '--hiera_config /opt/puphpet/puppet/hiera.yaml'
    synced_folder:
        folder1:
            id: webroot
            source: ./
            target: /var/www
            nfs: false
    post_up_message: ''
ssh:
    forward_agent: true
