imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@PuphpetBundle/Resources/config/services.yml" }

parameters:
    locale: en

framework:
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        name:        puphpet
        handler_id:  ~
    fragments:       ~
    http_method_override: true
    assets:
        version: "%assets_version%"

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: false

assetic:
    read_from: "%kernel.root_dir%/../web"
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    bundles:
        - PuphpetBundle
    filters:
        cssrewrite: ~
        jsqueeze: ~
        lessphp:
            apply_to: '\.less$'
            # Formatter options: compressed, lessjs, classic
            formatter: compressed
            preserve_comments: false
            formatter: 'Less_Parser'
