install: 0

settings:
    version: present
    default_vhost: 1
    proxy_buffers: 4 256k
    proxy_buffer_size: 128k
    proxy_connect_timeout: 600s
    proxy_send_timeout: 600s
    proxy_read_timeout: 600s
    names_hash_bucket_size: 128

upstreams: []

vhosts: []

proxies: []
