images:
    -
        image: dd844d58-8eac-4fa8-a44d-cd56105b12dd
        long_name: CentOS 7 (PVHVM)
    -
        image: 85e6f7c2-6ebc-47b5-af0b-28251fa91ca8
        long_name: Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
    -
        image: d97ba69f-b733-45be-8d60-4e415f4b0992
        long_name: Ubuntu 16.04 LTS (Xenial Xerus) (PVHVM)

sizes:
    - 512MB Standard Instance
    - 1GB Standard Instance
    - 2GB Standard Instance
    - 4GB Standard Instance
    - 8GB Standard Instance
    - 15GB Standard Instance
    - 30GB Standard Instance
    - 15 GB Compute v1
    - 30 GB Compute v1
    - 3.75 GB Compute v1
    - 60 GB Compute v1
    - 7.5 GB Compute v1
    - 1 GB General Purpose v1
    - 2 GB General Purpose v1
    - 4 GB General Purpose v1
    - 8 GB General Purpose v1
    - 120 GB I/O v1
    - 15 GB I/O v1
    - 30 GB I/O v1
    - 60 GB I/O v1
    - 90 GB I/O v1
    - 120 GB Memory v1
    - 15 GB Memory v1
    - 240 GB Memory v1
    - 30 GB Memory v1
    - 60 GB Memory v1
    - OnMetal General Purpose v2 Large
    - OnMetal General Purpose v2 Medium
    - OnMetal General Purpose v2 Small
    - OnMetal I/O v2
    - 1 GB Performance
    - 2 GB Performance
    - 4 GB Performance
    - 8 GB Performance
    - 120 GB Performance
    - 15 GB Performance
    - 30 GB Performance
    - 60 GB Performance
    - 90 GB Performance


regions:
    dfw: Dallas (DFW)
    ord: Chicago (ORD)
    iad: Northern Virginia (IAD)
    syd: Sydney (SYD)
    lon: London (LON)

empty_synced_folder:
    id: ~
    source: ~
    target: ~
    nfs: false

empty_machine:
    id: ~
    server_name: ~
    hostname: ~
    region: dfw
    size: 1GB Standard Instance
